Instructions

Your project will consist of 3 parts:

* Data: (3 points)
** DONE Describe how the observations in the sample are collected,
   CLOSED: [2017-04-02 Sun 12:02]
** DONE and the implications of this data collection method
   CLOSED: [2017-04-02 Sun 12:09]
on the scope of inference (generalizability / causality).:
*** Note that you might will need to look into documentation
on the BRFSS to answer this question. See http://www.cdc.gov/brfss/ as
well as the "More information on the data" section below.

* Research questions: (11 points)
** TODO Come up with at least three research questions
that you want to answer using these data.

- [ ] You should phrase your research questions in a way that matches up
  with the scope of inference your dataset allows for.
- [ ] Make sure that at least two of these questions involve at least
  three variables. You are welcomed to create new variables based on
  existing ones.
- [ ] With each question include a brief discussion (1-2 sentences) as to
  why this question is of interest to you and/or your audience.

- [ ] Question 1:
- [ ] Question 2:
- [ ] Question 3:

* EDA: (30 points)
** Perform exploratory data analysis (EDA) that addresses each of
the three research questions you outlined above.

- [ ] Your EDA should contain numerical summaries and visualizations.
- [ ] Each R output and plot should be accompanied by a brief interpretation.

* In addition to these parts, there are also 6 points allocated to
format, overall organization, and readability of your project. Total
points add up to 50 points. See the assessment rubric (provided above)
for more details on how your peers will evaluate your work.

* You can begin working on the project immediately.
Please save your work as you go along. When you're ready to submit
your work for evaluation, remember to click the "Submit" button.

* TODO After you submit your project, please provide feedback
to others on their projects. Please assess at least 3 projects. This
peer assessment will not only provide you with experience with a data
set and research questions but also prepare for your projects in the
future courses in the Specialization.


* Scoring (check all are addressed)
** Part 1: Data (3 points)
*** 2 pt for correct reasoning for generabizability 
– Answer should discuss whether random sampling was used. Learners
might discuss any reservations, those should be well justified.

*** 1 pt for correct reasoning for causality
– Answer should discuss whether random assignment was used.

** Part 2: Research questions (11 points)

***    3 pts for each research question (x 3)
- Should be phrased in a non-causal way (1 pt)
- Should be well defined / not vague (1 pt)
- Is clear why this is of interest to the author / audience (1 pt)
***    2 pts for at least two of the questions involving three variables

** Part 3: EDA (30 points)
*** 10 pts for each for each research question (x 3)
***     3 pts for plots
- Plots should address the research questions (1 pt)
- Plots should be constructed correctly (1 pt)
- Plots should be formatted well – size not too large, not too small, etc. (1 pt)
***     3 pts for summary statistics
- Summary statistics should address the research questions (1 pt)
- Summary statistics should be calculated correctly (1 pt)
- Summary statistics should be formatted well – not taking up pages and pages, etc. (1 pt)
***     4 pts for narrative
- Each plot and/or R output should be accompanied by a narrative (1 pt)
- Narrative should interpret the visuals / R output correctly (2 pts)
- Narrative should address the research question (1 pts)
** Overall (6 points)
*** Uploaded HTML document resulting from the Rmd template: 1 pt
*** Organization: 1 pts
*** Readability of the text: 2 pts
*** Readability of the code: 2 pts

* Notes
Try correlating:

Excellent health vs poor health for:
hours of sleep

Excellent health vs poor health for:
How Many Times Did You Eat Dark Green Vegetables?
How Many Times Did You Eat Beans Or Lentils?

Excellent health vs poor health for (choose two):
_bmi5: Computed Body Mass Index
_bmi5cat: Computed Body Mass Index Categories
_educag: Computed Level Of Education Completed Categories
_incomg: Computed Income Categories

1. For observations (respondents) who self-reported "Excellent" or
   "Poor" health, is there a correlation with the amount of sleep?

In the popular literature the amount of sleep one gets has been
associated with a weakened immune system, among other ailments. We are
curious if the observations correlate to this belief.

2. For observations (respondents) who self-reported "Excellent" or
   "Poor,"  did vegetable, fruit and bean consumption differ?

3. For respondents rated "Obese" by the BRFSS, many report themselves
   in "Excellent" health. Does reporting that they exercised in the
   past 30 days correlate to a positive answer?

Does having reported exercising correlate to the respondent's
perception of their general health, despite being categorized as
"Obese"?


